#!/bin/bash
# get current directory
CURR_DIR=$(pwd)
# get script dir
SCRIPT_DIR=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
# check args
if [ -z "$1" ]; then
	echo "Please include the plugin author's github username as first argument"
	exit 1
fi
if [ -z "$2" ]; then
	echo "Please include the plugin name as the second argument"
	exit 1
fi
if [ ! -z "$3" ]; then
	echo "Only two arguments are required"
	exit 1
fi
# move to script directory
cd $SCRIPT_DIR
# set plugin vars
GIT_REPO="$1/$2"
PLUGIN_PATH="$1/start"
PLUGIN_DIR="$PLUGIN_PATH/$2"
if [[ -d "$PLUGIN_PATH/.git" ]]; then
	echo "The repo for plugin \"$GIT_REPO\" may alredy be a submodule";
else
	echo "Adding submodule \"$GIT_REPO\""
	mkdir -p "$1/start" &&
		git submodule add "https://github.com/$GIT_REPO" "$PLUGIN_DIR" &&
		echo "Complete"
fi
cd "$CURR_DIR"
